name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Documentation tag or commit SHA to deploy'
        required: true
        type: string

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out documentation release
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Install, build, and upload your site
        uses: withastro/action@v6

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
